sludgerot/generator_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    # path('generate_video/', views.generate_video, name='generate_video'),
]

sludgerot/sludgerot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('generator_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sludgerot/generator_app/models.py
from django.db import models

# Create your models here.
from django.db import models

class UploadedClip(models.Model):
    clip = models.FileField(upload_to='clips/')



class SecondaryClip(models.Model):
    name = models.CharField(max_length=100, default='clip')
    clip = models.FileField(upload_to='secondary_clips/')


class VideoClip(models.Model):
    title = models.CharField(max_length=200)
    clip_file = models.FileField(upload_to='clips/')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title

sludgerot/generator_app/forms.py
from django import forms
from .models import UploadedClip, SecondaryClip

class UploadClipForm(forms.ModelForm):
    class Meta:
        model = UploadedClip
        fields = ['clip']

    def clean_clip(self):
        clip = self.cleaned_data.get("clip")
        if clip:
            if not clip.content_type.startswith('video/'):
                raise forms.ValidationError("File type is not a video.")
        return clip

class SelectSecondaryClipForm(forms.Form):
    CHOICES = [
        ('upload', 'Upload Your Own Clip'),
        ('select', 'Select From Available Clips'),
    ]
    option = forms.ChoiceField(choices=CHOICES)
    secondary_clip = forms.ModelChoiceField(queryset=SecondaryClip.objects.all())

sludgerot/generator_app/views.py
import logging

from django.http import JsonResponse
from django.shortcuts import render
from moviepy.editor import VideoFileClip, clips_array

from sludgerot.settings import MEDIA_ROOT
from .forms import UploadClipForm, SelectSecondaryClipForm
from .models import UploadedClip, SecondaryClip

logger = logging.getLogger(__name__)


def home(request):
    if request.method == 'POST':
        try:
            sec = request.POST.get('secondary_clip')
            if sec is None:
                return JsonResponse({'status': 'failure', 'message': 'Invalid form'})
            sec = int(sec)
            if 'clip' in request.FILES:  # Assuming 'clip' is the name of the file field in your form
                upload_form = UploadClipForm(request.POST, request.FILES)
                if upload_form.is_valid():
                    primary_clip = upload_form.save()
                    request.session['primary_clip_id'] = primary_clip.id
                    request.session['secondary_clip_id'] = sec
                    logger.info(f"Saved primary_clip_id in session: {primary_clip.id}")
                    out_path = generate_video(request)
                    if out_path['status'] == 'success':
                        return JsonResponse({'status': 'success', 'url': out_path['url']})
                    else:
                        return JsonResponse(out_path)
            return JsonResponse({'status': 'failure', 'message': 'Invalid form'})

        except Exception as e:
            return {'status': 'failure', 'message': str(e)}

    upload_form = UploadClipForm()
    select_form = SelectSecondaryClipForm()
    secondary_clips = SecondaryClip.objects.all()

    return render(request, 'generator_app/upload_clip.html', {
        'upload_form': upload_form,
        'select_form': select_form,
        'secondary_clips': secondary_clips,
    })


def generate_video(request):
    try:
        print("Session Data:", request.session.items())  # Debug print

        primary_clip_id = request.session.get('primary_clip_id')
        secondary_clip_id = request.session.get('secondary_clip_id')

        primary_clip = UploadedClip.objects.get(id=primary_clip_id)
        secondary_clip = SecondaryClip.objects.get(id=secondary_clip_id)

        primary_clip = VideoFileClip(primary_clip.clip.path)
        secondary_clip = VideoFileClip(secondary_clip.clip.path)

        # Determine the shorter of the two video durations
        min_duration = min(primary_clip.duration, secondary_clip.duration)

        # Trim both videos to the shorter duration
        primary_clip = primary_clip.subclip(0, min_duration)
        secondary_clip = secondary_clip.subclip(0, min_duration)

        # Set the desired width for both videos
        final_width = (500 * 9) // 16

        primary_clip = primary_clip.resize(width=final_width)
        # secondary_clip = secondary_clip.without_audio().resize(width=final_width)
        secondary_clip = secondary_clip.set_audio(None).resize(width=final_width)

        final_video = clips_array([[primary_clip], [secondary_clip]])
        output_path = MEDIA_ROOT + "/generated_clips/final" + str(primary_clip_id) + ".mp4"
        final_video.write_videofile(output_path, fps=30, threads=5, codec="libx264", audio_codec="aac",
                                    ffmpeg_params=["-crf", "23"])
        # final_video.write_videofile(output_path, fps=30, threads=5, codec="libx264", audio_codec="aac", ffmpeg_params=["-crf", "23"], logger=None)

        return {'status': 'success', "url": "/media/generated_clips/final" + str(primary_clip_id) + ".mp4"}

    except Exception as e:
        return {'status': 'failure', 'message': str(e)}

sludgerot/generator_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sludge Content Generator{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        label[for="id_clip"] {
            display: none;
        }

        #primary-clip-form {
            text-align: center;
        }

        #file-upload-wrapper {
            text-align: center;
        }
        
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="#">Sludge Generator</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <!-- Add more links here -->
                </ul>
            </div>
        </div>
    </nav>

    <main class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                {% block content %}
                <!-- Content will go here -->
                {% endblock %}
            </div>
        </div>
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

sludgerot/generator_app/templates/generator_app/upload_clip.html
{% extends 'base.html' %}

{% block content %}
    <style>
        .demo-container {
            width: 300px;
            margin: auto;
        }

        .progress-bar {
            height: 4px;
            background-color: rgba(5, 114, 206, 0.2);
            width: 100%;
            overflow: hidden;
        }

        .progress-bar-value {
            width: 100%;
            height: 100%;
            background-color: rgb(5, 114, 206);
            animation: indeterminateAnimation 1s infinite linear;
            transform-origin: 0% 50%;
        }

        table {
            width: auto; /* Set the width to "auto" */
            margin: 0 auto; /* Center the table horizontally */
        }

        @keyframes indeterminateAnimation {
            0% {
                transform: translateX(0) scaleX(0);
            }
            40% {
                transform: translateX(0) scaleX(0.4);
            }
            100% {
                transform: translateX(100%) scaleX(0.5);
            }
        }
    </style>
    <div style="text-align: center;">
        <div style="margin: 20px; padding: 20px;
        display: inline-block; border-radius: 8px;
        box-shadow: rgba(9, 30, 66, 0.25) 0px 4px 8px -2px, rgba(9, 30, 66, 0.08) 0px 0px 0px 1px;
        ">
            <form method="post" enctype="multipart/form-data" id="primary-clip-form">
                {% csrf_token %}
                <div>
                    <table style="font-size: 20px; letter-spacing: 1px; font-weight: 500">
                        <tr>
                            <td style="text-align: right; padding: 5px">
                                <label for="primaryFileInput">Primary Clip:</label>
                            </td>
                            <td style="text-align: left; padding: 5px">
                                <input style="width: 300px" name="clip" id="primaryFileInput" type="file"
                                       accept="video/*" required>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: right; padding: 5px">
                                <label for="secondary_clip_dropdown" style="text-align: right">Secondary Clip:</label>
                            </td>
                            <td style="text-align: left; padding: 5px">
                                <select name="secondary_clip" id="secondary_clip_dropdown">
                                    {% for clip in secondary_clips %}
                                        <option value="{{ clip.id }}">{{ clip.name }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                        </tr>
                    </table>
                    <button type="submit" id="sub_btn" class="btn btn-primary" style="margin: 10px">Generate</button>
                    <div id="progress_items" style="display: none">
                        <label style="font-size: 20px; letter-spacing: 1px; font-weight: 600; margin: 10px"
                               id="pro_label">Uploading video...</label><br>
                        {#                        <progress id="progress-bar" value="0" max="100"></progress>#}
                        <div class="demo-container">
                            <div class="progress-bar">
                                <div class="progress-bar-value"></div>
                            </div>
                        </div>
                    </div>
                </div>


            </form>
            <div id="vid-div" style="display: none;">
                <video id="vid" style="max-width: 250px; max-height: 700px" controls>
                    <source src="#" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
                <div style="width: 100%; text-align: center">
                    <a href="#" id="dn-btn" download>
                        <button class="btn btn-success" style="margin: 10px">Download Video</button>
                    </a>
                </div>
            </div>
        </div>

    </div>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const primaryForm = document.getElementById('primary-clip-form');
            const secondarySection = document.getElementById('secondary-section');
            const primaryFileInput = document.getElementById('primaryFileInput');

            primaryFileInput.addEventListener('change', async () => {
                document.getElementById('progress_items').style.display = 'none';
                document.getElementById('vid-div').style.display = 'none';
                var vid = document.getElementById('vid');
                vid.src = "#";
                vid.load();
                const file = primaryFileInput.files[0];
                if (file && file.type.startsWith('video/')) {
                    // Check the video duration
                    const video = document.createElement("video");
                    video.src = URL.createObjectURL(file);

                    video.onloadedmetadata = function () {
                        if (video.duration > 180) { // Check if duration is more than 3 minutes
                            alert("Please upload a video with a duration less than 3 minutes.");
                            primaryFileInput.value = ''; // Clear the input file
                            return;
                        }
                    };
                    secondarySection.style.display = 'inline-block';
                } else {
                    secondarySection.style.display = 'none';
                    alert("Please upload a video file.");
                    primaryFileInput.value = '';
                }
            });

            document.getElementById("primary-clip-form").addEventListener("submit", function (event) {
                // Prevent the default form submission behavior
                event.preventDefault();
                var form = document.getElementById("primary-clip-form");
                document.getElementById('progress_items').style.display = 'block';
                var formData = new FormData(form);
                document.getElementById('vid-div').style.display = 'none';
                var progressBar = document.getElementById("progress-bar");
                document.getElementById('primaryFileInput').setAttribute('disabled', "True");
                document.getElementById('secondary_clip_dropdown').setAttribute('disabled', "True");
                document.getElementById('sub_btn').setAttribute('disabled', "True");

                var xhr = new XMLHttpRequest();
                xhr.open("POST", "/home/", true);

                // Progress event handler
                xhr.upload.addEventListener("progress", function (e) {
                    if (e.lengthComputable) {
                        var percentComplete = (e.loaded / e.total) * 100;
                        {#progressBar.value = percentComplete;#}
                    }
                    if (percentComplete >= 100) {
                        document.getElementById('pro_label').innerText = "Mixing video clips..."
                    }
                });
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === 4 && xhr.status === 200) {
                        var resp = JSON.parse(xhr.responseText);
                        if (resp['status'] === "success") {
                            document.getElementById('vid-div').style.display = 'block';
                            var vid = document.getElementById('vid');
                            vid.src = resp['url'];
                            vid.load();
                            document.getElementById('dn-btn').setAttribute('href', resp['url']);
                        } else {
                            alert("Something went wrong, please try again later!\nError: " + resp['message'].toString())
                        }
                        document.getElementById('progress_items').style.display = 'none';
                        document.getElementById('primaryFileInput').removeAttribute('disabled');
                        document.getElementById('secondary_clip_dropdown').removeAttribute('disabled');
                        document.getElementById('sub_btn').removeAttribute('disabled');
                    }
                };
                xhr.onerror = function (e) {
                    alert("Something went wrong, please try again later!\nError: " + xhr.status.toString());
                    document.getElementById('progress_items').style.display = 'none';
                    document.getElementById('primaryFileInput').removeAttribute('disabled');
                    document.getElementById('secondary_clip_dropdown').removeAttribute('disabled');
                    document.getElementById('sub_btn').removeAttribute('disabled');
                };
                xhr.send(formData);

            });
        });

    </script>
{% endblock %}